### ISSUE TITLE
Using /dmh energy prevents you from shifting when not in cat form

### ISSUE THREAD

**Issue by vehystrix** [Korbrawr/DruidMacroHelper#1]
Because your energy is 100 when you're not in cat form, you cannot use the macro with `/dmh energy XX` in it to swap to cat form.

To fix it, I simply added a check to see if the current form is indeed cat form before checking for the energy level

return statement for the DruidEnergy function (lines 109-110) should be changed to :
```
return (preventShift > 0) or (UnitPower("player",0)<manaCost) or
    ((GetShapeshiftForm() == 3) and (UnitPower("player",3)>maxEnergy) and (DruidMacroLocShiftable() == 0));
```

**Comment by ForsakenNGS** [comment]
Will be fixed with the next release, thanks for the feedback!
