### ISSUE TITLE
Stuck in permanent autoUnshift = 0 after using this add-on

### ISSUE THREAD

**Issue by papa-smurf** [Korbrawr/DruidMacroHelper#11]
After only a few hours of using this add-on my character was stuck in a state where he would never automatically unshift for anything, whether it was a skill or (druid helper) macro, nothing worked.

I eventually ran `/run SetCVar("autoUnshift",1)` to get things back to normal.

This will no doubt be hard to debug, but with around 50 days played on lvl 70 and never running into this issue once before installing this add-on it seems too much of a coincidence for it not to be the culprit.

If there's anything you want me to try / test let me know.

**Comment by ForsakenNGS** [comment]
Sure you didn't just miss the `/dmh end` (which does set the CVar back to 1)? For debugging just type `/dmh debug` to enable debug mode, then you should see what the addon does step-by-step in chat.
