### ISSUE TITLE
Update to 1.1.9 throws LUA Errors

### ISSUE THREAD

**Issue by ap0yuv** [Korbrawr/DruidMacroHelper#14]
No expert in LUA but 

Line 160:
`  if ~UnitExists(unit) then`

and Line 165:
`if ~IsSpellInRange(L["SPELL_CHARGE"], unit) then` 

is throwing Error on WoW TBC Startup.

changing `~` to ` not ` fixes it for me , cus i suppose thats what the intention of those lines is ?

**Comment by Mushoz** [comment]
Same issue for me!

**Comment by HxxxxxS** [comment]
Yep this is some weird bug due to how lua handles types. I guess it is that `~` is oposite boolean but doesnt work with `nil`. Should be fixed with e81a219022bbc694d899384af649bc80abe52066

**Comment by ForsakenNGS** [comment]
Correct, as @HxxxxxS already mentioned I noticed and fixed that issue a few hours after the 1.1.9 release with Version 1.2.0
If you still have issues with this feel free to comment.
