### ISSUE TITLE
Feature request: Support for non-Dire Bear Form (level 10-39)

### ISSUE THREAD

**Issue by HxxxxxS** [Korbrawr/DruidMacroHelper#15]
Had someone ping me on Github for this. If anyone wanna implement this it'd be awesome. I don't have gametime currently. Probably wanna use either `UnitLevel("player")` or `IsSpellKnown()` and possibly add eventhandling for when someone learns Dire Bear Form mid session.

**Comment by ForsakenNGS** [comment]
Can you (or someone else) test the latest build? I don't have a druid in that range and am too lazy to do the 10 levels xD

**Comment by ForsakenNGS** [comment]
Also one TODO yet is to trigger `DruidMacroHelper:UpdateForms()` when new spells are learned for it to not require a reload upon learning the "Dire Bear Form".

**Comment by minorl** [comment]
@ForsakenNGS I confirmed this worked, level 35 bear. I'll try to remember to confirm if the auto update works when learning Dire Bear Form.

**Comment by minorl** [comment]
I had to reload to once I learned dire bear form.

**Comment by ForsakenNGS** [comment]
Should be close enough ;) Closing.
