### ISSUE TITLE
Is there a plan to release a wrath version?

### ISSUE THREAD

**Issue by superlahm** [Korbrawr/DruidMacroHelper#18]
I like the add-on very much in TBC. In Wrath, there is an updated cat rotation called bearweaving. Basically you use up almost all the energy and shift into bear form to apply lacerate DOT and maybe maul as well, and shift back to cat before the energy is full. So it is important to not shifting during gcd to avoid melee swing landing in caster form. It would be nice if this add-on supports Wrath so shifting during gcd can be easily prevented.

**Comment by ForsakenNGS** [comment]
The TBC version worked with wrath as well, but I recently updated the version number and deployment for wrath, so I'll close this :)
