### ISSUE TITLE
Any form to any form functionality?

### ISSUE THREAD

**Issue by trickdaemon** [Korbrawr/DruidMacroHelper#2]
Hi there, I'm trying to swap from psiloshift but noticing there isn't any function to go from form back to form like with psiloshift.

Any chance you could add this functionality? It's using the action bar paging stuff.

Thank you! 

"/click formStart
/click formEnd"

**Comment by HxxxxxS** [comment]
there is.
```
#showtooltip
/click dmhPot
/click dmhStart
/use [mod:shift]Major Healing Potion;Super Healing Potion
/click dmhEnd
```
they just use click instead of `/dmh`, kinda like the old one.

-Psilo

**Comment by trickdaemon** [comment]
Derp, thank you so much!
