### ISSUE TITLE
Be able to shift from flying flight form

### ISSUE THREAD

**Issue by OnceWasPerfect** [Korbrawr/DruidMacroHelper#9]
I would like to be able to directly shift from flight form while flying.  I often like to drop out of the air in cat form and immediately prowl.  Using the following 
```
#showtooltip
/dmh start
/cast !Cat Form
/dmh end
```  
Won't allow me to shift if i'm flying.  I get "You are in shapeshift form" error.  Note I can shift from flight form to cat using the macro if i'm on the ground.  I have also tried using /click dmhStart and /click dmhEnd but I get the same result.  

Thanks!

Edit:  I took a look through your code to see if I noticed anything obvious that is preventing it and I don't see anything.  I did find a work around if I put a /cancelform [noform: 3] or [noform:1] before the /click dmhStart it performs as desired.  It still doesn't explain why flight form works while on the ground and not in the air, but it's something.

**Comment by ForsakenNGS** [comment]
If you enable the "Auto Dismount in Flight" Option under "Interface > Game > Controls" it should work.
